[build]
builder = "nixpacks"

[deploy]
startCommand = "dotnet HRPerformance.Api.dll"
healthcheckPath = "/swagger"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
ASPNETCORE_ENVIRONMENT = "Production" 